# https://github.com/kentaro-m/auto-assign-action
addReviewers: true

# Set addAssignees to 'author' to set the PR creator as the assignee.
addAssignees: author

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 2

# Set to true to add assignees from different groups to pull requests
useAssigneeGroups: true

# A list of assignees, split into different froups, to be added to pull requests (GitHub user name)
assigneeGroups:
  {{ org }}:
    - platonfloria

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
 - wip
 - draft
