name: Test
on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.1
      with:
        token: ${{ secrets.PAT }}
        submodules: 'recursive'

    # - uses: satackey/action-docker-layer-caching@v0.0.11
    #   # Ignore the failure of a step and avoid terminating the job.
    #   continue-on-error: true

    - name: Build docker test image
      run: ./build.sh test

    - name: Run tests
      run: ./test.sh

    - name: Build docker prod image
      run: ./build.sh
      
    - name: Push image to Amazon ECR
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-west-1
        local-image: {{aws-id}}.dkr.ecr.eu-west-1.amazonaws.com/{{service-name}}:latest
        image: {{service-name}}:${{ github.sha }}
        
    - name: Checkout backend develop branch 
      uses: actions/checkout@v2
      with:
        repository: {{ioc-repo-name}}
        ref: develop
        token: ${{ secrets.PAT }}
        submodules: recursive
        path: backend
        fetch-depth: 0

    - name: install yq tool
      run: sudo snap install yq
       
    - name: Update docker manifest file
      run: |
         cd backend
         (cd {{service-name}}; git checkout ${{ github.sha }})
         git config user.email cicd@org.io
         git config user.name "cicd"
         git add . 
         git commit -m "updated {{service-name}} '${{ github.event.head_commit.message }}'"
         git push origin
